//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.14 at 10:44:28 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://codemark.ru/userssoapservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.codemark.userssoapservice;
